### ISSUE TITLE
Pricing or dates not updating? 

### ISSUE THREAD

**Issue by dpalecek** [scott113341/southwest-price-drop-bot#14]
Amazing service, thanks for all your work.

![swa](https://cloud.githubusercontent.com/assets/2923379/26073270/5890977c-397c-11e7-97ae-ff2fc47bc08f.png)

I've had this alert set since 5/9, but since then, I'm only seeing it say 5/9 across the x-axis. Is this just because the price hasn't changed since 5/9 and it's just not updating the date until the price changes or is this a bug?

**Comment by rusd11** [comment]
I have seen a similar issue to prices not reflecting the accurate flight price and displaying an older price. It will update if I open "Alert Details" > "Edit" > "Save Changes" and wait a few minutes. My deployment varies from the deployment notes of "Add an hourly task that runs npm run task:check" by having mine set to a task every 10 minutes. Logs appear to me as showing the prices are being checked successfully though. Here's a sample of the logs: 
» 16 May 2017 12:13:15.916 155 <45>1 2017-05-16T17:13:15.618109+00:00 heroku scheduler.7824 - - Starting process with command `npm run task:check`
» 16 May 2017 12:13:16.499 138 <45>1 2017-05-16T17:13:16.271453+00:00 heroku scheduler.7824 - - State changed from starting to up
» 16 May 2017 12:13:18.447 103 <190>1 2017-05-16T17:13:18.076125+00:00 app scheduler.7824 - -
» 16 May 2017 12:13:18.522 151 <190>1 2017-05-16T17:13:18.076166+00:00 app scheduler.7824 - - > southwest-price-drop-bot@1.7.1 task:check /app
» 16 May 2017 12:13:18.522 141 <190>1 2017-05-16T17:13:18.076173+00:00 app scheduler.7824 - - > node --trace-warnings tasks/check.js
» 16 May 2017 12:13:18.522 103 <190>1 2017-05-16T17:13:18.076174+00:00 app scheduler.7824 - -
» 16 May 2017 12:13:19.482 122 <190>1 2017-05-16T17:13:19.084312+00:00 app scheduler.7824 - - checking 10 flights
» 16 May 2017 12:13:22.152 144 <190>1 2017-05-16T17:13:21.781492+00:00 app scheduler.7824 - - */**/2017 #***** DAL → JAX not cheaper
» 16 May 2017 12:13:22.223 141 <190>1 2017-05-16T17:13:22.023336+00:00 app scheduler.7824 - - */**/2017 #***** DAL → DTW not cheaper
» 16 May 2017 12:13:22.644 145 <190>1 2017-05-16T17:13:22.347887+00:00 app scheduler.7824 - - */**/2017 #***** JAX → DAL not cheaper
» 16 May 2017 12:13:23.450 140 <190>1 2017-05-16T17:13:22.890166+00:00 app scheduler.7824 - - */**/2017 #***** DAL → DTW not cheaper
» 16 May 2017 12:13:23.454 142 <190>1 2017-05-16T17:13:23.151170+00:00 app scheduler.7824 - - */**/2017 #**** ATL → DAL not cheaper
» 16 May 2017 12:13:23.526 141 <190>1 2017-05-16T17:13:22.890198+00:00 app scheduler.7824 - - */**/2017 #***** DTW → DAL not cheaper
» 16 May 2017 12:13:23.526 142 <190>1 2017-05-16T17:13:22.891352+00:00 app scheduler.7824 - - */**/2017 #***** DTW → DAL not cheaper
» 16 May 2017 12:13:23.537 141 <190>1 2017-05-16T17:13:23.389733+00:00 app scheduler.7824 - - */**/2017 #***** DAL → ATL not cheaper
» 16 May 2017 12:13:24.208 142 <190>1 2017-05-16T17:13:23.714822+00:00 app scheduler.7824 - - */**/2017 #***** DAL → ATL not cheaper
» 16 May 2017 12:13:24.293 142 <190>1 2017-05-16T17:13:24.007785+00:00 app scheduler.7824 - - */**/2017 #***** ATL → DAL not cheaper
» 16 May 2017 12:13:24.479 138 <45>1 2017-05-16T17:13:24.276777+00:00 heroku scheduler.7824 - - State changed from up to complete
» 16 May 2017 12:13:24.554 133 <45>1 2017-05-16T17:13:24.258803+00:00 heroku scheduler.7824 - - Process exited with status 0
» 16 May 2017 12:13:45.177 417 <134>1 2017-05-16T17:13:42+00:00 app heroku-redis - - source=REDIS sample%23active-connections=4 sample%23load-avg-1m=0.24 sample%23load-avg-5m=0.17 sample%23load-avg-15m=0.115 sample%23read-iops=0 sample%23write-iops=0 sample%23memory-total=15664292kB sample%23memory-free=12353832kB sample%23memory-cached=1328256kB sample%23memory-redis=352888bytes sample%23hit-rate=0.99994 sample%23evicted-keys=0

**Comment by scott113341** [comment]
Hi @dpalecek, can you double-check that you have completed steps 3 and 4 from the readme:

> 3. Open up the Heroku Scheduler from your app's dashboard
> 4. Add an hourly task that runs npm run task:check

The behavior you describe would occur had you forgotten to manually set up the scheduled task to check for price drops!

**Comment by scott113341** [comment]
@rusd11, I just pushed up some changes that fix an issue that I think you are experiencing when updating alerts.  There was a bug that would create duplicate alerts when editing and saving an existing one, fixed in [this commit](https://github.com/scott113341/southwest-price-drop-bot/commit/878cea0960a47ac49a772b82ed979f7fb95ba6cd).  Additionally, I added a check that will clear out the price history when updating an alert if the date, to, from, or flight number change when saving in [this commit](https://github.com/scott113341/southwest-price-drop-bot/commit/ea15434f6e2b3d631c3b7fee4d9205da20f3aa09).  Once you've updated your instance, please let me know if you are still having issues with the prices not updating.  Thanks!

**Comment by scott113341** [comment]
Closing for now, feel free to ping or re-open if you continue hitting this issue
