### ISSUE TITLE
Not getting alert when price drop

### ISSUE THREAD

**Issue by tjs198** [scott113341/southwest-price-drop-bot#17]
So I believe I set everything up correctly, I got a text say 'Alert created for Southwest flight . . . ."

I just checked and the price bot app picked up a lower price but i never got a text - what can be wrong?
![text-alert](https://user-images.githubusercontent.com/16629715/29482259-31c9a37e-845c-11e7-9739-32fb150320a5.jpg)
![southwest_price_drop_bot](https://user-images.githubusercontent.com/16629715/29482261-385eb8e6-845c-11e7-8a5b-84827ec7b437.jpg)

**Comment by tjs198** [comment]
sorry, was my cell service provider - cricket sucks!  went changed to verizon, it works great

**Comment by scott113341** [comment]
Good to hear this was just a carrier issue, let me know if you run into any other trouble @tjs198
