### ISSUE TITLE
Updating (Non-bug)

### ISSUE THREAD

**Issue by reallydontbotherme** [scott113341/southwest-price-drop-bot#20]
Hi, sorry if this is not the place for this, but I'm struggling to figure out how to push your changes via the CLI to my heroku App. Is there a certain set of commands I should be doing that I can run through? Everything is installed, but I'm clueless on the next steps. 

Love your app, but nuking and pushing new deployments every time there is an update is obviously not the right way. :(

Is it possible to link to the github repo instead via the heroku site?

Thank you!

**Comment by reallydontbotherme** [comment]
I think I it figured out, the basic CLI instructions below are pasted in case anyone else is braindead like me:

$ heroku login
$ heroku git:clone -a YOUR-APP-NAME
$ cd YOUR-APP-NAME

Download the latest version from Scott (thanks again!) and copy it into that folder above.

$ git add .
$ git commit -am "make it better"
$ git push heroku master

That should push the newest version live. At least I believe so!

**Comment by scott113341** [comment]
Glad you figured it out @reallydontbotherme, though there is one optimization you can make to this process.  Instead of downloading/copying the code from GitHub anytime there is an update, you can simply add this repository as a git remote and let git handle the process for you!

```
heroku login
heroku git:clone -a YOUR-APP-NAME
cd YOUR-APP-NAME
git remote add origin git@github.com:scott113341/southwest-price-drop-bot.git
```

And then whenever you want to update:

```
git pull origin master
git push heroku master
```

**Comment by reallydontbotherme** [comment]
No dice unfortunately on the pull, not sure if its a permission thing on my end or yours? Probably mine!

C:\xx\xxxx>git pull origin master
Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by scott113341** [comment]
This is probably because you don't have SSH keys set up on GitHub.  Try this:

```
git remote remove origin
git remote add origin https://github.com/scott113341/southwest-price-drop-bot.git
git pull origin master
```

That'll remove the SSH-based git remote and replace it with an HTTPS-based git remote that doesn't require any additional setup.
